// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"database/sql"
	"time"
)

type Task struct {
	ID           int32        `json:"id"`
	Pid          string       `json:"pid"`
	CreatedAt    time.Time    `json:"created_at"`
	TechnicianID int32        `json:"technician_id"`
	Summary      string       `json:"summary"`
	Status       string       `json:"status"`
	CompletedAt  sql.NullTime `json:"completed_at"`
}

type User struct {
	ID        int32     `json:"id"`
	Pid       string    `json:"pid"`
	CreatedAt time.Time `json:"created_at"`
	Username  string    `json:"username"`
	Password  string    `json:"password"`
	Role      string    `json:"role"`
}
